Fix method generation for those who don't have arguments
phpro/soap-client pull request #315
Opened 2020-09-11 11:32 UTC by whatUwant

2020-09-21 06:56 UTC, whatUwant commented
Any update on this PR? @veewee @janvernieuwe

2020-09-21 10:32 UTC, veewee commented
Thanks for the PR @whatUwant. We will review it shortly!

2020-09-25 08:44 UTC, janvernieuwe requested changes
Hi @whatUwant 

Thank you very much for your PR, it's looking good.

Could you change the big ternary to a private method?
This would improve readability a lot.

2020-09-25 08:44 UTC, janvernieuwe commented on src/Phpro/SoapClient/CodeGenerator/Assembler/ClientMethodAssembler.php
> +            $methodBody = $param === null ?
Perhaps move this to a private method with early returns?

2020-09-25 10:41 UTC, janvernieuwe approved these changes

2020-09-25 10:41 UTC, merged

2020-09-25 10:48 UTC, janvernieuwe commented
Thank you!