#446: Add check for available classes.
phpro/soap-client pull request #447
Opened 2022-09-02 09:44 UTC by yenyasinn

2022-09-02 09:59 UTC, ademarco requested changes

2022-09-02 09:59 UTC, ademarco commented on src/Phpro/SoapClient/CodeGenerator/Util/TypeChecker.php
> +        if (preg_match('/^\\\[A-Z0-9]{1,}[a-zA-Z0-9\\\]+$/', $type)) {
I've tested the regex above on https://regex101.com/ and it didn't seem to work well. The suggested one below works and covers more cases:

```suggestion
        if (preg_match('/^\\?[a-zA-Z0-9_]{1,}[a-zA-Z0-9_\\]+$/', $type)) {
```

2022-09-02 09:59 UTC, ademarco commented on test/PhproTest/SoapClient/Unit/CodeGenerator/Util/TypeCheckerTest.php
> +            ['\KnownClass', true],
We could add these cases here as well, so that we check the regex more thoroughly:
```
class_name
CalssName
\class_name
\CalssName
class_name\class_name
CalssName\className
\class_name\class_name
\CalssName\className\fdsaa
```

2022-09-02 12:22 UTC, yenyasinn commented on src/Phpro/SoapClient/CodeGenerator/Util/TypeChecker.php
> +        if (preg_match('/^\\\[A-Z0-9]{1,}[a-zA-Z0-9\\\]+$/', $type)) {
I've updated regular expression - lower case characters in the beginning of class and underscore are allowed. But I left check that class name has to be started with `\`

2022-09-30 07:19 UTC, veewee commented
Closing this one in favour for #448

2022-09-30 07:19 UTC, closed without merging